version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           apt-get -y update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install bc build-essential bison flex zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd openjdk-11-jdk openjdk-11-jre
           git clone --depth=1 https://github.com/azrim/kernel_xiaomi_ginkgo.git -b $CIRCLE_BRANCH ginkgo
           cd ginkgo
           git clone https://github.com/azrim/myscripts.git -b master
           chmod +x myscripts/envsetup.sh
           chmod +x myscripts/circle.sh
           source ./myscripts/envsetup.sh
           ./myscripts/circle.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
